export const OBSERVABILITY_SCHEMA_VERSION = 1 as const;

export const OBSERVABILITY_LOCAL_FILE = ".harness/observability.local.json";

export const P_DEV_OBSERVABILITY_SESSION_ID_ENV =
  "P_DEV_OBSERVABILITY_SESSION_ID";
export const P_DEV_OBSERVABILITY_NONCE_ENV = "P_DEV_OBSERVABILITY_NONCE";

export const P_DEV_OBSERVABILITY_DISABLED_ENV = "P_DEV_OBSERVABILITY_DISABLED";
export const P_DEV_SENTRY_DISABLED_ENV = "P_DEV_SENTRY_DISABLED";
export const P_DEV_ANALYTICS_DISABLED_ENV = "P_DEV_ANALYTICS_DISABLED";

export const P_DEV_SENTRY_DSN_ENV = "P_DEV_SENTRY_DSN";
export const P_DEV_POSTHOG_PROJECT_TOKEN_ENV = "P_DEV_POSTHOG_PROJECT_TOKEN";
export const P_DEV_POSTHOG_HOST_ENV = "P_DEV_POSTHOG_HOST";
export const P_DEV_SENTRY_ENVIRONMENT_ENV = "P_DEV_SENTRY_ENVIRONMENT";
export const P_DEV_RELEASE_SHA_ENV = "P_DEV_RELEASE_SHA";

export const OBSERVABILITY_PUBLIC_CONFIG_FILENAME = "observability.public.json";
export const TRACKED_OBSERVABILITY_PUBLIC_CONFIG_RELATIVE =
  "config/observability.public.json";

export const OBSERVABILITY_FLUSH_DEADLINE_MS = 1_000;
export const OBSERVABILITY_MAX_QUEUE_SIZE = 32;
export const OBSERVABILITY_REQUEST_MAX_BYTES = 8_192;
