import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("server-only", () => ({}));

vi.mock("../../src/workflow-page/linear-status-source.js", () => ({
  loadLiveLinearStatuses: vi.fn(async () => ({
    statuses: [{ id: "s1", name: "Todo", type: "unstarted" }],
    loadState: "loaded",
  })),
}));

vi.mock("../../src/workflow-page/model-catalog.js", () => ({
  fetchLiveCursorModelCatalog: vi.fn(async () => ({
    catalog: [
      {
        id: "composer-2.5",
        displayName: "Composer 2.5",
        availability: "available",
        supportedParameters: [],
        source: "cursor-live",
      },
    ],
    loadState: "loaded",
  })),
}));

vi.mock("../../src/setup/credential-health.js", async () => {
  const actual = await vi.importActual<
    typeof import("../../src/setup/credential-health.js")
  >("../../src/setup/credential-health.js");
  return {
    ...actual,
    verifyAllSavedCredentialHealth: vi.fn(async () => ({
      LINEAR_API_KEY: { status: "connected", message: "ok" },
      CURSOR_API_KEY: { status: "connected", message: "ok" },
      GITHUB_TOKEN: { status: "connected", message: "ok" },
      VERCEL_TOKEN: { status: "connected", message: "ok" },
    })),
    verifySavedCredentialHealth: vi.fn(async () => ({
      status: "connected",
      message: "ok",
    })),
  };
});

import { loadWorkflowBootstrap } from "../../apps/gui/lib/workflow-server.js";
import { GET as getBootstrap } from "../../apps/gui/app/api/workflow/bootstrap/route.ts";
import { POST as postVerifySaved } from "../../apps/gui/app/api/setup/verify-saved-connections/route.ts";
import { writeControlPlaneSetupState } from "../../src/setup/control-plane-setup-state.js";

const CANARIES = {
  LINEAR_API_KEY: "SECRET_CANARY_LINEAR_workflow_leak_test_001",
  CURSOR_API_KEY: "SECRET_CANARY_CURSOR_workflow_leak_test_001",
  GITHUB_TOKEN: "SECRET_CANARY_GITHUB_workflow_leak_test_001",
  VERCEL_TOKEN: "SECRET_CANARY_VERCEL_workflow_leak_test_001",
  LINEAR_WEBHOOK_SECRET: "SECRET_CANARY_WEBHOOK_workflow_leak_test_001",
} as const;

const ENV_COMMENT = "# Operator local setup — generated by harness setup core";
const ENV_DO_NOT_COMMIT = "# Do not commit .env.local (gitignored).";

const CONFIG_JSON = JSON.stringify(
  {
    version: 1,
    orchestratorMarker: "harness-orchestrator-v1",
    logDirectory: "runs",
    repos: [
      {
        id: "my-product",
        linearProjects: ["My Product"],
        targetRepo: "https://github.com/acme/my-product",
        baseBranch: "dev",
        productionBranch: "main",
      },
    ],
    allowedTargetRepos: ["https://github.com/acme/my-product"],
    linear: { teamKey: "WES" },
  },
  null,
  2,
);

function assertNoCanaries(serialized: string): void {
  for (const value of Object.values(CANARIES)) {
    expect(serialized).not.toContain(value);
  }
  expect(serialized).not.toContain(ENV_COMMENT);
  expect(serialized).not.toContain(ENV_DO_NOT_COMMIT);
  expect(serialized).not.toContain("LINEAR_API_KEY=");
  expect(serialized).not.toContain("CURSOR_API_KEY=");
  expect(serialized).not.toContain("GITHUB_TOKEN=");
  expect(serialized).not.toContain("VERCEL_TOKEN=");
  expect(serialized).not.toContain("LINEAR_WEBHOOK_SECRET=");
}

describe("workflow secret canary boundary", () => {
  let operatorRoot = "";
  let previousRepoRoot: string | undefined;
  let previousDevHome: string | undefined;
  const logs: string[] = [];
  let logSpy: ReturnType<typeof vi.spyOn> | undefined;
  let errorSpy: ReturnType<typeof vi.spyOn> | undefined;

  beforeEach(async () => {
    previousRepoRoot = process.env.HARNESS_REPO_ROOT;
    previousDevHome = process.env.P_DEV_HOME;
    operatorRoot = await mkdtemp(path.join(tmpdir(), "workflow-canary-"));
    process.env.P_DEV_HOME = operatorRoot;
    process.env.HARNESS_REPO_ROOT = operatorRoot;

    await mkdir(path.join(operatorRoot, ".harness"), { recursive: true });
    await writeFile(
      path.join(operatorRoot, ".env.local"),
      [
        ENV_COMMENT,
        ENV_DO_NOT_COMMIT,
        "",
        "HARNESS_CONFIG_PATH=.harness/config.local.json",
        `LINEAR_API_KEY=${CANARIES.LINEAR_API_KEY}`,
        `CURSOR_API_KEY=${CANARIES.CURSOR_API_KEY}`,
        `GITHUB_TOKEN=${CANARIES.GITHUB_TOKEN}`,
        `VERCEL_TOKEN=${CANARIES.VERCEL_TOKEN}`,
        `LINEAR_WEBHOOK_SECRET=${CANARIES.LINEAR_WEBHOOK_SECRET}`,
      ].join("\n"),
      "utf8",
    );
    await writeFile(
      path.join(operatorRoot, ".harness", "config.local.json"),
      CONFIG_JSON,
      "utf8",
    );
    await writeControlPlaneSetupState(
      {
        version: 1,
        linear: {
          teamId: "team-123",
          teamKey: "WES",
          teamName: "Weston",
        },
        initialSetup: {
          status: "complete",
          completedAt: new Date().toISOString(),
          completionEvidence: {
            localConfigPresent: true,
            linearConfigured: true,
            vercelConfigured: true,
            cloudSecretsVerified: true,
            targetWorkflowsVerified: true,
          },
        },
      },
      operatorRoot,
    );

    logs.length = 0;
    logSpy = vi.spyOn(console, "log").mockImplementation((...args) => {
      logs.push(args.map(String).join(" "));
    });
    errorSpy = vi.spyOn(console, "error").mockImplementation((...args) => {
      logs.push(args.map(String).join(" "));
    });
  });

  afterEach(async () => {
    logSpy?.mockRestore();
    errorSpy?.mockRestore();
    if (previousRepoRoot === undefined) {
      delete process.env.HARNESS_REPO_ROOT;
    } else {
      process.env.HARNESS_REPO_ROOT = previousRepoRoot;
    }
    if (previousDevHome === undefined) {
      delete process.env.P_DEV_HOME;
    } else {
      process.env.P_DEV_HOME = previousDevHome;
    }
    await rm(operatorRoot, { recursive: true, force: true });
  });

  it("keeps canaries and raw env lines out of workflow bootstrap serialization", async () => {
    const payload = await loadWorkflowBootstrap({
      source: null,
      fixture: null,
      scope: "my-product",
    });
    const serialized = JSON.stringify(payload);

    assertNoCanaries(serialized);
    expect(payload.sourceMode).toBe("live");
    expect(payload.selectedScopeId).toBe("my-product");
    expect(payload.plannerSelection.modelId).toBeTruthy();
    expect(payload.configFingerprint.length).toBeGreaterThan(0);

    for (const line of logs) {
      assertNoCanaries(line);
    }
  });

  it("keeps canaries out of bootstrap API JSON responses", async () => {
    const response = await getBootstrap(
      new Request(
        "http://localhost/api/workflow/bootstrap?scope=my-product",
      ),
    );
    expect(response.status).toBe(200);
    const body = await response.text();
    assertNoCanaries(body);
    const parsed = JSON.parse(body) as { selectedScopeId?: string };
    expect(parsed.selectedScopeId).toBe("my-product");
  });

  it("keeps canaries out of connection-health API responses", async () => {
    const response = await postVerifySaved(
      new Request("http://localhost/api/setup/verify-saved-connections", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({}),
      }),
    );
    const body = await response.text();
    assertNoCanaries(body);
    // Key names may appear as map keys; values must not.
    expect(body).not.toContain(CANARIES.VERCEL_TOKEN);
  });

  it("uses RSC-safe sync reads for env and config on the workflow path", () => {
    const repoRoot = path.resolve(
      path.dirname(fileURLToPath(import.meta.url)),
      "../..",
    );
    const envMerge = readFileSync(
      path.join(repoRoot, "src/setup/env-merge.ts"),
      "utf8",
    );
    const rscSafe = readFileSync(
      path.join(repoRoot, "src/setup/rsc-safe-fs.ts"),
      "utf8",
    );
    const workflowServer = readFileSync(
      path.join(repoRoot, "apps/gui/lib/workflow-server.ts"),
      "utf8",
    );

    expect(rscSafe).toContain("readFileSync");
    expect(envMerge).toContain("readTextFileSyncIfExists");
    expect(envMerge).not.toMatch(/from "node:fs\/promises"[\s\S]*readFile/);
    expect(workflowServer).toContain("toPublicWorkflowBootstrap");
  });
});
