/**
 * Machine-readable inventory of the current product-development lifecycle.
 * Used by tests and ADR documentation.
 */

export interface WorkflowLifecycleInventoryEntry {
  statusName: string;
  statusId: string;
  owner: "agent" | "human" | "orchestrator" | "terminal";
  trigger: string;
  runner: string | null;
  agentRole: string | null;
  promptRole: string | null;
  modelRole: string | null;
  allowedNextStatusNames: string[];
  retryBehavior: string;
  idempotencyKey: string | null;
  reconciliation: string;
  langfusePhase: string | null;
  posthogSentry: string;
}

export const CURRENT_WORKFLOW_INVENTORY: readonly WorkflowLifecycleInventoryEntry[] =
  [
    {
      statusName: "Ready for Planning",
      statusId: "ready-for-planning",
      owner: "orchestrator",
      trigger: "webhook dispatch-trigger",
      runner: "planning",
      agentRole: "planner",
      promptRole: "planner",
      modelRole: "planner",
      allowedNextStatusNames: ["Planning", "Blocked"],
      retryBehavior: "idempotent on planning completion marker",
      idempotencyKey: "planning_completion",
      reconciliation: "live status eligible for planning dispatch",
      langfusePhase: "planning",
      posthogSentry: "bounded phase/run metadata only",
    },
    {
      statusName: "Planning",
      statusId: "planning",
      owner: "agent",
      trigger: "claimed by planning runner",
      runner: "planning",
      agentRole: "planner",
      promptRole: "planner",
      modelRole: "planner",
      allowedNextStatusNames: ["Ready for Build", "Plan Review", "Blocked"],
      retryBehavior: "failure → Blocked after claim",
      idempotencyKey: "planning_completion",
      reconciliation: "in-progress; no webhook re-dispatch",
      langfusePhase: "planning",
      posthogSentry: "bounded phase/run metadata only",
    },
    {
      statusName: "Ready for Build",
      statusId: "ready-for-build",
      owner: "orchestrator",
      trigger: "webhook dispatch-trigger",
      runner: "implementation",
      agentRole: "builder",
      promptRole: "implementer",
      modelRole: "builder",
      allowedNextStatusNames: ["Building", "Ready for Planning", "Blocked"],
      retryBehavior: "uninitialized product may reroute to planning",
      idempotencyKey: "implementation_start + open PR",
      reconciliation: "live status eligible for implementation",
      langfusePhase: "implementation",
      posthogSentry: "bounded phase/run metadata only",
    },
    {
      statusName: "Plan Review",
      statusId: "plan-review",
      owner: "agent",
      trigger: "optional; only when effectively enabled after planning",
      runner: "plan_review",
      agentRole: "plan_reviewer",
      promptRole: "plan_reviewer",
      modelRole: "plan_reviewer",
      allowedNextStatusNames: ["Ready for Build", "Planning", "Blocked"],
      retryBehavior: "infra failure stays in Plan Review; no cycle increment",
      idempotencyKey: "plan_review_decision",
      reconciliation: "review decision + plan artifact identity",
      langfusePhase: "plan_review",
      posthogSentry: "bounded readiness/transition metadata only",
    },
    {
      statusName: "Building",
      statusId: "building",
      owner: "agent",
      trigger: "claimed by implementation runner",
      runner: "implementation",
      agentRole: "builder",
      promptRole: "implementer",
      modelRole: "builder",
      allowedNextStatusNames: ["PR Open", "Blocked"],
      retryBehavior: "stale implementation_start allows recovery; open PR → handoff",
      idempotencyKey: "implementation_start",
      reconciliation: "building recovery routing",
      langfusePhase: "implementation",
      posthogSentry: "bounded phase/run metadata only",
    },
    {
      statusName: "PR Open",
      statusId: "pr-open",
      owner: "orchestrator",
      trigger: "harness-owned post-build (not bridge dispatch)",
      runner: "handoff",
      agentRole: null,
      promptRole: null,
      modelRole: null,
      allowedNextStatusNames: ["PM Review", "Code Review", "Blocked"],
      retryBehavior: "idempotent on handoff completion marker",
      idempotencyKey: "handoff_completion",
      reconciliation: "live status + PR evidence",
      langfusePhase: "handoff",
      posthogSentry: "bounded phase/run metadata only",
    },
    {
      statusName: "Code Review",
      statusId: "code-review",
      owner: "agent",
      trigger:
        "explicit durable code_review job after post-build; reconciler redispatches if missing",
      runner: "code_review",
      agentRole: "code_reviewer",
      promptRole: "code_reviewer",
      modelRole: "code_reviewer",
      allowedNextStatusNames: ["PM Review", "Code Revision", "Blocked"],
      retryBehavior: "infra/eligibility failure stays recoverable; no cycle increment",
      idempotencyKey: "code_review_decision",
      reconciliation: "review decision + PR artifact identity",
      langfusePhase: "code_review",
      posthogSentry: "bounded readiness/eligibility/transition metadata only",
    },
    {
      statusName: "Code Revision",
      statusId: "code-revision",
      owner: "agent",
      trigger: "optional; Code Review needs_revision when configuredReady",
      runner: "code_revision",
      agentRole: "builder",
      promptRole: "code_reviser",
      modelRole: "code_reviser",
      allowedNextStatusNames: ["Code Review", "Blocked"],
      retryBehavior: "infra failure stays in Code Revision; no cycle increment",
      idempotencyKey: "code_revision_run",
      reconciliation: "PR head + review decision linkage",
      langfusePhase: "code_revision",
      posthogSentry: "bounded readiness/eligibility/transition metadata only",
    },
    {
      statusName: "PM Review",
      statusId: "pm-review",
      owner: "human",
      trigger: "none (human gate)",
      runner: null,
      agentRole: null,
      promptRole: null,
      modelRole: null,
      allowedNextStatusNames: ["Needs Revision", "Engineering Review"],
      retryBehavior: "human decision",
      idempotencyKey: null,
      reconciliation: "not automation-eligible",
      langfusePhase: null,
      posthogSentry: "no automation events",
    },
    {
      statusName: "Needs Revision",
      statusId: "needs-revision",
      owner: "orchestrator",
      trigger: "webhook + revision reconcile",
      runner: "revision",
      agentRole: "builder",
      promptRole: "reviser",
      modelRole: "builder",
      allowedNextStatusNames: ["Revising", "Blocked"],
      retryBehavior: "keyed by pmFeedbackCommentId",
      idempotencyKey: "pmFeedbackCommentId",
      reconciliation: "evaluateRevisionReconcile",
      langfusePhase: "revision",
      posthogSentry: "bounded phase/run metadata only",
    },
    {
      statusName: "Revising",
      statusId: "revising",
      owner: "agent",
      trigger: "claimed by revision runner",
      runner: "revision",
      agentRole: "builder",
      promptRole: "reviser",
      modelRole: "builder",
      allowedNextStatusNames: ["PM Review", "Code Review", "Blocked"],
      retryBehavior: "failure → Blocked after claim",
      idempotencyKey: "pmFeedbackCommentId",
      reconciliation: "in-progress",
      langfusePhase: "revision",
      posthogSentry: "bounded phase/run metadata only",
    },
    {
      statusName: "Engineering Review",
      statusId: "engineering-review",
      owner: "human",
      trigger: "none (human gate)",
      runner: null,
      agentRole: null,
      promptRole: null,
      modelRole: null,
      allowedNextStatusNames: ["Needs Revision", "Ready to Merge"],
      retryBehavior: "human decision",
      idempotencyKey: null,
      reconciliation: "not automation-eligible",
      langfusePhase: null,
      posthogSentry: "no automation events",
    },
    {
      statusName: "Ready to Merge",
      statusId: "ready-to-merge",
      owner: "orchestrator",
      trigger: "webhook + merge reconcile",
      runner: "merge",
      agentRole: null,
      promptRole: null,
      modelRole: null,
      allowedNextStatusNames: ["Merging", "Blocked"],
      retryBehavior: "keyed by issueKey+prUrl",
      idempotencyKey: "issueKey+prUrl",
      reconciliation: "evaluateMergeReconcile",
      langfusePhase: "merge",
      posthogSentry: "bounded phase/run metadata only",
    },
    {
      statusName: "Merging",
      statusId: "merging",
      owner: "orchestrator",
      trigger: "claimed by merge runner (+ integration repair)",
      runner: "merge / integration-repair",
      agentRole: "builder",
      promptRole: "integration_repairer",
      modelRole: "builder",
      allowedNextStatusNames: ["Merged to Dev", "Merged / Deployed", "Blocked"],
      retryBehavior: "repairCycleId; stay in Merging during repair",
      idempotencyKey: "issueKey+prUrl+repairCycleId",
      reconciliation: "merge recovery paths",
      langfusePhase: "merge",
      posthogSentry: "bounded phase/run metadata only",
    },
    {
      statusName: "Merged to Dev",
      statusId: "merged-to-dev",
      owner: "orchestrator",
      trigger: "production_promoted dispatch",
      runner: "production_sync",
      agentRole: null,
      promptRole: null,
      modelRole: null,
      allowedNextStatusNames: ["Merged / Deployed"],
      retryBehavior: "keyed by mergeCommitSha",
      idempotencyKey: "mergeCommitSha",
      reconciliation: "production sync idempotency",
      langfusePhase: "production_sync",
      posthogSentry: "bounded phase/run metadata only",
    },
    {
      statusName: "Merged / Deployed",
      statusId: "merged-deployed",
      owner: "terminal",
      trigger: "none",
      runner: null,
      agentRole: null,
      promptRole: null,
      modelRole: null,
      allowedNextStatusNames: [],
      retryBehavior: "terminal",
      idempotencyKey: null,
      reconciliation: "terminal",
      langfusePhase: null,
      posthogSentry: "no automation events",
    },
    {
      statusName: "Blocked",
      statusId: "blocked",
      owner: "terminal",
      trigger: "phase failure / failure-finalization",
      runner: null,
      agentRole: null,
      promptRole: null,
      modelRole: null,
      allowedNextStatusNames: [],
      retryBehavior: "human recovery",
      idempotencyKey: null,
      reconciliation: "terminal failure",
      langfusePhase: null,
      posthogSentry: "error context only",
    },
  ] as const;
