/**
 * Product-development workflow definition v2.
 * New workspaces enable Plan Review and Code Review; legacy configs without a
 * workflow section keep both disabled via LEGACY_WORKFLOW_MIGRATION_DEFAULTS.
 */

import type {
  WorkflowDefinition,
  WorkflowLoopCounterDefinition,
  WorkflowPhaseDefinition,
  WorkflowStatusDefinition,
  WorkflowTransitionDefinition,
} from "./types.js";
import { PRODUCT_DEVELOPMENT_ROLE_MAPPINGS } from "./roles.js";

export const WORKFLOW_SCHEMA_VERSION = "product-development-v2";

/** Defaults written into brand-new first-run harness configs. */
export const NEW_WORKSPACE_OPTIONAL_PHASE_DEFAULTS = {
  planReview: true,
  codeReview: true,
} as const;

/**
 * Fallbacks when migrating configs that omit workflow.optionalPhases.
 * Preserves pre-Chunk-8 behavior (reviews off) for legacy installations.
 */
export const LEGACY_WORKFLOW_MIGRATION_DEFAULTS = {
  planReview: false,
  codeReview: false,
} as const;

export const DEFAULT_CYCLE_LIMITS = {
  plan_review_cycles: 4,
  code_review_cycles: 4,
} as const;

const STATUSES: readonly WorkflowStatusDefinition[] = [
  {
    id: "backlog",
    name: "Backlog",
    category: "backlog",
    owner: "human",
    automationTrigger: false,
    creatable: true,
    systemManaged: false,
  },
  {
    id: "ready-for-planning",
    name: "Ready for Planning",
    category: "unstarted",
    owner: "orchestrator",
    automationTrigger: true,
    creatable: true,
    systemManaged: false,
  },
  {
    id: "planning",
    name: "Planning",
    category: "started",
    owner: "agent",
    automationTrigger: false,
    creatable: true,
    systemManaged: false,
  },
  {
    id: "plan-review",
    name: "Plan Review",
    category: "started",
    owner: "agent",
    automationTrigger: false,
    creatable: true,
    systemManaged: false,
    optionalPhaseId: "plan_review",
  },
  {
    id: "ready-for-build",
    name: "Ready for Build",
    category: "unstarted",
    owner: "orchestrator",
    automationTrigger: true,
    creatable: true,
    systemManaged: false,
  },
  {
    id: "building",
    name: "Building",
    category: "started",
    owner: "agent",
    automationTrigger: false,
    creatable: true,
    systemManaged: false,
  },
  {
    id: "pr-open",
    name: "PR Open",
    category: "started",
    owner: "orchestrator",
    automationTrigger: true,
    creatable: true,
    systemManaged: false,
  },
  {
    id: "code-review",
    name: "Code Review",
    category: "started",
    owner: "agent",
    automationTrigger: false,
    creatable: true,
    systemManaged: false,
    optionalPhaseId: "code_review",
  },
  {
    id: "code-revision",
    name: "Code Revision",
    category: "started",
    owner: "agent",
    automationTrigger: false,
    creatable: true,
    systemManaged: false,
    optionalPhaseId: "code_review",
  },
  {
    id: "pm-review",
    name: "PM Review",
    category: "started",
    owner: "human",
    automationTrigger: false,
    creatable: true,
    systemManaged: false,
  },
  {
    id: "engineering-review",
    name: "Engineering Review",
    category: "started",
    owner: "human",
    automationTrigger: false,
    creatable: true,
    systemManaged: false,
  },
  {
    id: "needs-revision",
    name: "Needs Revision",
    category: "unstarted",
    owner: "orchestrator",
    automationTrigger: true,
    creatable: true,
    systemManaged: false,
  },
  {
    id: "revising",
    name: "Revising",
    category: "started",
    owner: "agent",
    automationTrigger: false,
    creatable: true,
    systemManaged: false,
  },
  {
    id: "ready-to-merge",
    name: "Ready to Merge",
    category: "started",
    owner: "orchestrator",
    automationTrigger: true,
    creatable: true,
    systemManaged: false,
  },
  {
    id: "merging",
    name: "Merging",
    category: "started",
    owner: "orchestrator",
    automationTrigger: false,
    creatable: true,
    systemManaged: false,
  },
  {
    id: "merged-to-dev",
    name: "Merged to Dev",
    category: "completed",
    owner: "orchestrator",
    automationTrigger: false,
    creatable: true,
    systemManaged: false,
  },
  {
    id: "merged-deployed",
    name: "Merged / Deployed",
    category: "completed",
    owner: "terminal",
    automationTrigger: false,
    creatable: true,
    systemManaged: false,
  },
  {
    id: "blocked",
    name: "Blocked",
    category: "started",
    owner: "terminal",
    automationTrigger: false,
    creatable: true,
    systemManaged: false,
  },
  {
    id: "canceled",
    name: "Canceled",
    category: "canceled",
    owner: "terminal",
    automationTrigger: false,
    creatable: true,
    systemManaged: false,
  },
  {
    id: "duplicate",
    name: "Duplicate",
    category: "duplicate",
    owner: "terminal",
    automationTrigger: false,
    creatable: false,
    systemManaged: true,
  },
] as const;

const PHASES: readonly WorkflowPhaseDefinition[] = [
  {
    id: "backlog",
    status: "backlog",
    owner: "human",
    optional: false,
    label: "Backlog triage",
    defaultNext: "planning_dispatch",
    decisions: [
      {
        id: "approved",
        label: "Ready for Planning",
        nextPhaseId: "planning_dispatch",
      },
      {
        id: "needs_revision",
        label: "Ready for Build",
        nextPhaseId: "implementation_dispatch",
      },
    ],
  },
  {
    id: "planning_dispatch",
    status: "ready-for-planning",
    owner: "orchestrator",
    optional: false,
    label: "Ready for Planning",
    agentRole: "planner",
    promptRole: "planner",
    skillRole: "planner",
    modelRole: "planner",
    defaultNext: "planning",
    inProgressStatus: "planning",
    failureNext: "blocked",
    evaluationPhase: "planning",
    reconciliation: {
      eligible: true,
      evidenceKeys: ["issue_status"],
    },
  },
  {
    id: "planning",
    status: "planning",
    owner: "agent",
    optional: false,
    label: "Planning",
    agentRole: "planner",
    promptRole: "planner",
    skillRole: "planner",
    modelRole: "planner",
    defaultNext: "plan_review",
    bypassNext: "implementation_dispatch",
    failureNext: "blocked",
    evaluationPhase: "planning",
  },
  {
    id: "plan_review",
    status: "plan-review",
    owner: "agent",
    optional: true,
    enabledBy: "optionalPhases.planReview",
    label: "Plan Review",
    agentRole: "plan_reviewer",
    promptRole: "plan_reviewer",
    skillRole: "plan_reviewer",
    modelRole: "plan_reviewer",
    bypassNext: "implementation_dispatch",
    defaultNext: "implementation_dispatch",
    retryTarget: "planning",
    maximumCycles: 4,
    cycleCounter: "plan_review_cycles",
    evaluationPhase: "plan_review",
    requiresLinearStatus: false,
    decisions: [
      {
        id: "approved",
        label: "Approve plan",
        nextPhaseId: "implementation_dispatch",
      },
      {
        id: "needs_revision",
        label: "Revise plan",
        nextPhaseId: "planning_dispatch",
        incrementsCycleCounter: true,
      },
    ],
    reconciliation: {
      eligible: true,
      evidenceKeys: ["issue_status", "review_decision"],
    },
  },
  {
    id: "implementation_dispatch",
    status: "ready-for-build",
    owner: "orchestrator",
    optional: false,
    label: "Ready for Build",
    agentRole: "builder",
    promptRole: "implementer",
    skillRole: "implementation",
    modelRole: "builder",
    defaultNext: "implementation",
    inProgressStatus: "building",
    failureNext: "blocked",
    evaluationPhase: "implementation",
    reconciliation: {
      eligible: true,
      evidenceKeys: ["issue_status"],
    },
  },
  {
    id: "implementation",
    status: "building",
    owner: "agent",
    optional: false,
    label: "Implementation",
    agentRole: "builder",
    promptRole: "implementer",
    skillRole: "implementation",
    modelRole: "builder",
    defaultNext: "handoff",
    failureNext: "blocked",
    evaluationPhase: "implementation",
  },
  {
    id: "handoff",
    status: "pr-open",
    owner: "orchestrator",
    optional: false,
    label: "Handoff",
    defaultNext: "code_review",
    bypassNext: "pm_review",
    failureNext: "blocked",
    evaluationPhase: "handoff",
    reconciliation: {
      eligible: true,
      evidenceKeys: ["issue_status", "pr_url"],
    },
  },
  {
    id: "code_review",
    status: "code-review",
    owner: "agent",
    optional: true,
    enabledBy: "optionalPhases.codeReview",
    label: "Code Review",
    agentRole: "code_reviewer",
    promptRole: "code_reviewer",
    skillRole: "code_reviewer",
    modelRole: "code_reviewer",
    bypassNext: "pm_review",
    defaultNext: "pm_review",
    retryTarget: "code_revision",
    maximumCycles: 4,
    cycleCounter: "code_review_cycles",
    evaluationPhase: "code_review",
    requiresLinearStatus: false,
    decisions: [
      {
        id: "approved",
        label: "Approve code",
        nextPhaseId: "pm_review",
      },
      {
        id: "needs_revision",
        label: "Needs revision",
        nextPhaseId: "code_revision",
        incrementsCycleCounter: true,
      },
    ],
    reconciliation: {
      eligible: true,
      evidenceKeys: ["issue_status", "pr_url", "review_decision"],
    },
  },
  {
    id: "code_revision",
    status: "code-revision",
    owner: "agent",
    optional: true,
    enabledBy: "optionalPhases.codeReview",
    label: "Code Revision",
    agentRole: "builder",
    promptRole: "code_reviser",
    skillRole: "implementation",
    modelRole: "code_reviser",
    bypassNext: "pm_review",
    defaultNext: "code_review",
    failureNext: "code_revision",
    evaluationPhase: "code_revision",
    requiresLinearStatus: false,
    reconciliation: {
      eligible: true,
      evidenceKeys: ["issue_status", "pr_url", "review_decision"],
    },
  },
  {
    id: "pm_review",
    status: "pm-review",
    owner: "human",
    optional: false,
    label: "PM Review",
    decisions: [
      {
        id: "needs_revision",
        label: "Needs Revision",
        nextPhaseId: "revision_dispatch",
      },
      {
        id: "approved",
        label: "Engineering Review",
        nextPhaseId: "engineering_review",
      },
    ],
  },
  {
    id: "engineering_review",
    status: "engineering-review",
    owner: "human",
    optional: false,
    label: "Engineering Review",
    decisions: [
      {
        id: "needs_revision",
        label: "Needs Revision",
        nextPhaseId: "revision_dispatch",
      },
      {
        id: "approved",
        label: "Ready to Merge",
        nextPhaseId: "merge_dispatch",
      },
    ],
  },
  {
    id: "revision_dispatch",
    status: "needs-revision",
    owner: "orchestrator",
    optional: false,
    label: "Needs Revision",
    agentRole: "builder",
    promptRole: "reviser",
    skillRole: "implementation",
    modelRole: "builder",
    defaultNext: "revision",
    inProgressStatus: "revising",
    failureNext: "blocked",
    evaluationPhase: "revision",
    reconciliation: {
      eligible: true,
      evidenceKeys: ["issue_status", "pm_feedback_comment_id"],
    },
  },
  {
    id: "revision",
    status: "revising",
    owner: "agent",
    optional: false,
    label: "Revision",
    agentRole: "builder",
    promptRole: "reviser",
    skillRole: "implementation",
    modelRole: "builder",
    defaultNext: "code_review",
    bypassNext: "pm_review",
    failureNext: "blocked",
    evaluationPhase: "revision",
  },
  {
    id: "merge_dispatch",
    status: "ready-to-merge",
    owner: "orchestrator",
    optional: false,
    label: "Ready to Merge",
    defaultNext: "merge",
    inProgressStatus: "merging",
    failureNext: "blocked",
    evaluationPhase: "merge",
    reconciliation: {
      eligible: true,
      evidenceKeys: ["issue_status", "pr_url", "merge_source"],
    },
  },
  {
    id: "merge",
    status: "merging",
    owner: "orchestrator",
    optional: false,
    label: "Merging",
    defaultNext: "merged_to_dev",
    failureNext: "blocked",
    evaluationPhase: "merge",
  },
  {
    id: "integration_repair",
    status: "merging",
    owner: "agent",
    optional: false,
    label: "Merge integration repair",
    agentRole: "builder",
    promptRole: "integration_repairer",
    skillRole: "implementation",
    modelRole: "builder",
    defaultNext: "merge",
    failureNext: "blocked",
    evaluationPhase: "merge",
  },
  {
    id: "merged_to_dev",
    status: "merged-to-dev",
    owner: "orchestrator",
    optional: false,
    label: "Merged to Dev",
    defaultNext: "merged_deployed",
    evaluationPhase: "production_sync",
    reconciliation: {
      eligible: true,
      evidenceKeys: ["issue_status", "merge_commit_sha"],
    },
  },
  {
    id: "production_sync",
    status: "merged-to-dev",
    owner: "orchestrator",
    optional: false,
    label: "Production sync",
    defaultNext: "merged_deployed",
    evaluationPhase: "production_sync",
  },
  {
    id: "merged_deployed",
    status: "merged-deployed",
    owner: "terminal",
    optional: false,
    label: "Merged / Deployed",
  },
  {
    id: "blocked",
    status: "blocked",
    owner: "terminal",
    optional: false,
    label: "Blocked",
  },
  {
    id: "canceled",
    status: "canceled",
    owner: "terminal",
    optional: false,
    label: "Canceled",
  },
  {
    id: "duplicate",
    status: "duplicate",
    owner: "terminal",
    optional: false,
    label: "Duplicate",
  },
] as const;

const TRANSITIONS: readonly WorkflowTransitionDefinition[] = [
  {
    id: "planning_claim",
    fromPhaseId: "planning_dispatch",
    toPhaseId: "planning",
    kind: "system",
    label: "Planning",
  },
  {
    id: "planning_success_bypass",
    fromPhaseId: "planning",
    toPhaseId: "implementation_dispatch",
    kind: "bypass",
    label: "Ready for Build",
    whenOptionalEnabled: false,
  },
  {
    id: "planning_success_to_plan_review",
    fromPhaseId: "planning",
    toPhaseId: "plan_review",
    kind: "success",
    label: "Plan Review",
    whenOptionalEnabled: true,
  },
  {
    id: "planning_failure",
    fromPhaseId: "planning",
    toPhaseId: "blocked",
    kind: "failure",
    label: "Blocked",
  },
  {
    id: "plan_review_approved",
    fromPhaseId: "plan_review",
    toPhaseId: "implementation_dispatch",
    kind: "review_approved",
    label: "Ready for Build",
    decisionId: "approved",
  },
  {
    id: "plan_review_needs_revision",
    fromPhaseId: "plan_review",
    // Route to dispatch (Ready for Planning), not in-progress Planning.
    // Planning eligibility only claims from Ready for Planning; landing on
    // Planning caused silent wrong_status skips and stuck revision loops.
    toPhaseId: "planning_dispatch",
    kind: "review_needs_revision",
    label: "Ready for Planning",
    decisionId: "needs_revision",
  },
  {
    id: "plan_review_escalation",
    fromPhaseId: "plan_review",
    toPhaseId: "blocked",
    kind: "escalation",
    label: "Blocked",
  },
  {
    id: "implementation_claim",
    fromPhaseId: "implementation_dispatch",
    toPhaseId: "implementation",
    kind: "system",
    label: "Building",
  },
  {
    id: "implementation_success",
    fromPhaseId: "implementation",
    toPhaseId: "handoff",
    kind: "success",
    label: "PR Open",
  },
  {
    id: "implementation_failure",
    fromPhaseId: "implementation",
    toPhaseId: "blocked",
    kind: "failure",
    label: "Blocked",
  },
  {
    id: "handoff_success_bypass",
    fromPhaseId: "handoff",
    toPhaseId: "pm_review",
    kind: "bypass",
    label: "PM Review",
    whenOptionalEnabled: false,
  },
  {
    id: "handoff_success_to_code_review",
    fromPhaseId: "handoff",
    toPhaseId: "code_review",
    kind: "success",
    label: "Code Review",
    whenOptionalEnabled: true,
  },
  {
    id: "handoff_failure",
    fromPhaseId: "handoff",
    toPhaseId: "blocked",
    kind: "failure",
    label: "Blocked",
  },
  {
    id: "code_review_approved",
    fromPhaseId: "code_review",
    toPhaseId: "pm_review",
    kind: "review_approved",
    label: "PM Review",
    decisionId: "approved",
  },
  {
    id: "code_review_needs_revision",
    fromPhaseId: "code_review",
    toPhaseId: "code_revision",
    kind: "review_needs_revision",
    label: "Code Revision",
    decisionId: "needs_revision",
  },
  {
    id: "code_review_escalation",
    fromPhaseId: "code_review",
    toPhaseId: "blocked",
    kind: "escalation",
    label: "Blocked",
  },
  {
    id: "code_revision_success",
    fromPhaseId: "code_revision",
    toPhaseId: "code_review",
    kind: "success",
    label: "Code Review",
  },
  {
    id: "code_revision_failure",
    fromPhaseId: "code_revision",
    toPhaseId: "code_revision",
    kind: "failure",
    label: "Code Revision",
  },
  {
    id: "revision_claim",
    fromPhaseId: "revision_dispatch",
    toPhaseId: "revision",
    kind: "system",
    label: "Revising",
  },
  {
    id: "revision_success_bypass",
    fromPhaseId: "revision",
    toPhaseId: "pm_review",
    kind: "bypass",
    label: "PM Review",
    whenOptionalEnabled: false,
  },
  {
    id: "revision_success_to_code_review",
    fromPhaseId: "revision",
    toPhaseId: "code_review",
    kind: "success",
    label: "Code Review",
    whenOptionalEnabled: true,
  },
  {
    id: "revision_failure",
    fromPhaseId: "revision",
    toPhaseId: "blocked",
    kind: "failure",
    label: "Blocked",
  },
  {
    id: "pm_to_needs_revision",
    fromPhaseId: "pm_review",
    toPhaseId: "revision_dispatch",
    kind: "human",
    label: "Needs Revision",
    decisionId: "needs_revision",
  },
  {
    id: "pm_to_engineering",
    fromPhaseId: "pm_review",
    toPhaseId: "engineering_review",
    kind: "human",
    label: "Engineering Review",
    decisionId: "approved",
  },
  {
    id: "eng_to_needs_revision",
    fromPhaseId: "engineering_review",
    toPhaseId: "revision_dispatch",
    kind: "human",
    label: "Needs Revision",
    decisionId: "needs_revision",
  },
  {
    id: "eng_to_ready_to_merge",
    fromPhaseId: "engineering_review",
    toPhaseId: "merge_dispatch",
    kind: "human",
    label: "Ready to Merge",
    decisionId: "approved",
  },
  {
    id: "merge_claim",
    fromPhaseId: "merge_dispatch",
    toPhaseId: "merge",
    kind: "system",
    label: "Merging",
  },
  {
    id: "merge_to_dev",
    fromPhaseId: "merge",
    toPhaseId: "merged_to_dev",
    kind: "success",
    label: "Merged to Dev",
  },
  {
    id: "merge_direct_production",
    fromPhaseId: "merge",
    toPhaseId: "merged_deployed",
    kind: "success",
    label: "Merged / Deployed",
  },
  {
    id: "merge_failure",
    fromPhaseId: "merge",
    toPhaseId: "blocked",
    kind: "failure",
    label: "Blocked",
  },
  {
    id: "production_sync_success",
    fromPhaseId: "merged_to_dev",
    toPhaseId: "merged_deployed",
    kind: "system",
    label: "Merged / Deployed",
  },
  {
    id: "backlog_to_planning",
    fromPhaseId: "backlog",
    toPhaseId: "planning_dispatch",
    kind: "human",
    label: "Ready for Planning",
  },
  {
    id: "backlog_to_build",
    fromPhaseId: "backlog",
    toPhaseId: "implementation_dispatch",
    kind: "human",
    label: "Ready for Build",
  },
] as const;

const LOOP_COUNTERS: readonly WorkflowLoopCounterDefinition[] = [
  {
    id: "plan_review_cycles",
    label: "Plan review cycles",
    defaultMaximum: DEFAULT_CYCLE_LIMITS.plan_review_cycles,
    scope: "issue",
  },
  {
    id: "code_review_cycles",
    label: "Code review cycles",
    defaultMaximum: DEFAULT_CYCLE_LIMITS.code_review_cycles,
    scope: "issue",
  },
] as const;

export const PRODUCT_DEVELOPMENT_WORKFLOW_V2: WorkflowDefinition = {
  schemaVersion: WORKFLOW_SCHEMA_VERSION,
  id: "product-development",
  label: "Product development",
  statuses: STATUSES,
  phases: PHASES,
  transitions: TRANSITIONS,
  loopCounters: LOOP_COUNTERS,
  roleBindings: PRODUCT_DEVELOPMENT_ROLE_MAPPINGS.map((m) => ({
    statusId: m.statusId,
    phaseId: m.phaseId,
    agentRole: m.agentRole,
    promptRole: m.promptRole,
    skillRole: m.skillRole,
    modelRole: m.modelRole ?? undefined,
  })),
  terminalPhaseIds: ["merged_deployed", "blocked", "canceled", "duplicate"],
  dispatchTriggerStatusIds: [
    "ready-for-planning",
    "ready-for-build",
    "pr-open",
    "needs-revision",
    "ready-to-merge",
  ],
};

export function lookupPhase(
  definition: WorkflowDefinition,
  phaseId: string,
): WorkflowPhaseDefinition | undefined {
  return definition.phases.find((phase) => phase.id === phaseId);
}

export function lookupStatus(
  definition: WorkflowDefinition,
  statusId: string,
): WorkflowStatusDefinition | undefined {
  return definition.statuses.find((status) => status.id === statusId);
}

export function lookupStatusByName(
  definition: WorkflowDefinition,
  name: string,
): WorkflowStatusDefinition | undefined {
  const normalized = name.trim().toLowerCase();
  return definition.statuses.find(
    (status) => status.name.toLowerCase() === normalized,
  );
}

export function phaseIdForStatusId(
  definition: WorkflowDefinition,
  statusId: string,
): string | undefined {
  const binding = definition.roleBindings.find((b) => b.statusId === statusId);
  if (binding) return binding.phaseId;
  const phase = definition.phases.find((p) => p.status === statusId);
  return phase?.id;
}
